version: '2'

services:
        demo:
                build: opentracing_demo/.
                ports: 
                        - "8080:8080"
                environment: 
                        - JAEGER_SERVICE_NAME=hello_service
                        # - JAEGER_AGENT_HOST=53.52.34.56
                        # - JAEGER_AGENT_PORT=6831
                        - JAEGER_ENDPOINT=http://53.52.34.56:14268/api/traces
        jaeger: 
                image: jaegertracing/all-in-one:latest
                ports:
                        - "5775:5775/udp"
                        - "6831:6831/udp"
                        - "6832:6832/udp"
                        - "5778:5778"
                        - "16686:16686"
                        - "14268:14268"
                        - "9411:9411"